name: stripe_clean_architecture
description: A clean architecture implementation of Stripe API using Dart.
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.8.0"

dependencies:
  http: ^1.3.0
  dotenv: ^4.2.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
