/// Represents a PaymentIntent object from Stripe.
///
/// A PaymentIntent tracks the process of collecting a payment from a customer.
/// It holds the unique identifier of the payment intent.
class PaymentIntent {
  /// Creates a [PaymentIntent] instance.
  ///
  /// The [id] parameter is required and represents the unique identifier
  /// of the PaymentIntent as provided by Stripe.
  PaymentIntent({required this.id});

  /// The unique identifier of the PaymentIntent.
  ///
  /// This ID is generated by Stripe and is used to reference the PaymentIntent
  /// in subsequent API calls.
  final String id;
}
